name: CI/CD Pipeline

on:
  push:
    branches: ['main', 'feature/initial-layout']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check syntax
        run: php -l index.php

      - name: Install dependencies
        run: echo "No dependencies to install" # Просто виведе текст, щоб крок був зеленим

      - name: Run tests
        run: php index.php
